# Synthetic Data Generation Configuration
# Cheese Manufacturing Database - Taleggio Production

database:
  path: "db/cheese_manufacturing.db"
  backup_before_generation: true
  backup_path: "db/backups/"

generation:
  # Time and Scale Parameters
  time_span:
    start_date: "2024-01-01"
    end_date: "2024-01-31"
    days: 31
    lots_per_day: 1
    total_lots: 31

  # Core Architecture (Schema 01)
  core:
    lot_count: 31
    date_range_days: 31
    product_codes: ["TALEGGIO"]
    facility_codes: ["FAC001"]
    batch_size_kg_range: [45.0, 55.0]

  # Raw Materials & Suppliers (Schema 02)
  raw_materials:
    supplier_count: 4
    raw_lot_count: 93
    milk_test_count: 29
    ingredient_test_count: 41
    supplier_types:
      - "DAIRY_FARM"
      - "INGREDIENT"
      - "PACKAGING"
      - "EQUIPMENT"

  # Preprocessing Operations (Schema 03)
  preprocessing:
    batch_count: 117
    pasteurization_records_per_batch: 5
    standardization_records_per_batch: 3
    process_types:
      - "PASTEURIZATION"
      - "STANDARDIZATION"
      - "SEPARATION"

  # Manufacturing Process (Schema 04)
  manufacturing:
    batch_count: 496
    coagulation_records_per_batch: 1
    curd_records_per_batch: 1
    pressing_records_per_batch: 1
    cheese_types: ["TALEGGIO"]
    
    # Taleggio-specific parameters
    taleggio_process:
      milk_quantity_liters: 50
      target_temp_celsius: 40
      acidification_time_minutes: 40
      rennet_amount_cc: 10
      rennet_titer: "1:20,000"
      first_cut_rest_minutes: 10
      second_cut_rest_minutes: 17
      target_curd_size: "hazelnut"
      stufatura_temp_celsius: 35
      target_ph_stufatura: 5.3

  # Aging & Maturation (Schema 05)
  aging:
    cave_count: 3
    environmental_readings_per_cave_per_day: 24
    activities_per_lot: 10
    cave_types:
      - "NATURAL"
      - "CONTROLLED"
      - "SURFACE_RIPENING"
    
    # Taleggio aging parameters
    taleggio_aging:
      initial_aging_days: 15
      initial_temp_celsius: 4
      final_temp_celsius: 10
      humidity_percentage: 80
      washing_frequency: 3
      washing_period_days: 10
      washing_solution: "Salt solution with Brevibacterium linens"

  # Quality Control & Testing (Schema 06)
  quality:
    test_methods_count: 10
    tests_per_lot: 5
    composition_tests_per_lot: 10
    microbiology_tests_per_lot: 15
    test_categories:
      - "COMPOSITION"
      - "MICROBIOLOGY"
      - "PHYSICAL"
      - "SENSORY"
    
    # Quality standards
    quality_standards:
      ph_min: 5.8
      ph_max: 6.2
      moisture_min: 45.0
      moisture_max: 55.0
      fat_min: 25.0
      fat_max: 35.0

  # Sensory Analysis (Schema 07)
  sensory:
    panel_count: 5
    panelist_count: 8
    attributes_count: 10
    evaluations_per_lot: 1

  # Packaging Operations (Schema 08)
  packaging:
    line_count: 5
    materials_count: 8
    runs_per_lot: 5
    packages_per_run: 10
    operations_per_lot: 4
    
    # Packaging steps
    packaging_steps:
      - "CUTTING"
      - "VACUUM_SEALING"
      - "LABELING"
      - "BOXING"

  # Labeling & Regulatory (Schema 09)
  labeling:
    regulatory_records_per_lot: 1
    label_types:
      - "PRODUCT_LABEL"
      - "NUTRITION_LABEL"
      - "ALLERGEN_LABEL"

  # Weighing & Pricing (Schema 10)
  weighing:
    equipment_count: 6
    pricing_rules_count: 6
    catch_weight_transactions_per_lot: 10
    inventory_transactions_per_lot: 10

  # Shipping & Logistics (Schema 11)
  shipping:
    carrier_count: 6
    shipments_per_lot: 10
    temperature_monitoring_readings_per_shipment: 600
    delivery_confirmations_per_shipment: 1

# Data Quality Settings
data_quality:
  # Realistic progression settings
  realistic_progression: true
  chronological_flow: true
  uuid_consistency: true
  
  # Process accuracy
  taleggio_specific: true
  proper_aging_timeline: true
  environmental_monitoring: true
  
  # Data integrity
  foreign_key_integrity: true
  no_empty_tables: true
  proper_date_sequences: true

# Logging Configuration
logging:
  level: "INFO"
  file: "data_generation.log"
  console_output: true
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 